# Generated by Django 6.0.5 on 2026-05-29 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie_recommender", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watcher",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
    ]
